/**
 * Report export utilities
 *
 *   exportAsPDF(title, html)   → opens a clean printable preview, user picks "Save as PDF"
 *                                in the browser print dialog (works everywhere, no CDN needed)
 *   exportAsWord(title, html)  → downloads a .doc file (HTML payload, opens in Word / Google Docs)
 *
 * `html` should be a string of trusted HTML for the BODY of the report
 * (header is provided automatically). Keep it simple — basic tags, tables, images.
 */

const REPORT_STYLES = `
  @page { margin: 16mm; }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    color: #1f2937;
    margin: 0;
    padding: 24px;
    line-height: 1.55;
  }
  .report-header {
    border-bottom: 3px solid #2e7d32;
    padding-bottom: 14px;
    margin-bottom: 22px;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    gap: 20px;
  }
  .report-brand {
    font-size: 14px;
    color: #2e7d32;
    font-weight: 700;
    letter-spacing: 0.04em;
    text-transform: uppercase;
  }
  .report-meta {
    font-size: 11px;
    color: #6b7280;
    text-align: right;
  }
  h1.report-title {
    margin: 6px 0 0 0;
    font-size: 26px;
    color: #111827;
  }
  h2 { color: #111827; font-size: 18px; margin: 22px 0 8px 0; padding-bottom: 6px; border-bottom: 1px solid #e5e7eb; }
  h3 { color: #111827; font-size: 14px; margin: 14px 0 6px 0; }
  p, li { font-size: 12.5px; color: #374151; }
  small { color: #6b7280; }

  table { width: 100%; border-collapse: collapse; margin: 8px 0 18px 0; font-size: 12px; }
  th, td { border: 1px solid #e5e7eb; padding: 8px 10px; text-align: left; vertical-align: top; }
  th { background: #f0fdf4; color: #166534; font-weight: 700; }
  tr:nth-child(even) td { background: #fafafa; }

  .stat-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 8px 0 18px 0; }
  .stat-card {
    border: 1px solid #e5e7eb;
    border-left: 4px solid #2e7d32;
    border-radius: 6px;
    padding: 10px 14px;
  }
  .stat-card .num { font-size: 22px; font-weight: 700; color: #111827; }
  .stat-card .lbl { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.04em; }

  .badge {
    display: inline-block;
    padding: 2px 8px;
    background: #d1fae5;
    color: #166534;
    border-radius: 999px;
    font-size: 11px;
    font-weight: 600;
  }

  .plant-image {
    width: 100%;
    max-width: 320px;
    height: auto;
    border-radius: 6px;
    border: 1px solid #e5e7eb;
    margin: 4px 0 16px 0;
  }

  .report-footer {
    margin-top: 28px;
    padding-top: 12px;
    border-top: 1px solid #e5e7eb;
    font-size: 11px;
    color: #9ca3af;
    text-align: center;
  }

  /* Hide stuff when printing */
  @media print {
    .no-print { display: none !important; }
    body { padding: 0; }
  }
`;

const TODAY_LONG = () => {
  const d = new Date();
  return d.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
};

/**
 * Wrap user content with a consistent header/footer + styles
 */
function buildHtmlDocument(title, bodyHtml) {
  const safeTitle = String(title || 'Report').replace(/</g, '&lt;');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${safeTitle}</title>
  <style>${REPORT_STYLES}</style>
</head>
<body>
  <div class="report-header">
    <div>
      <div class="report-brand">🌿 Botanic Journal</div>
      <h1 class="report-title">${safeTitle}</h1>
    </div>
    <div class="report-meta">
      Generated<br/><strong>${TODAY_LONG()}</strong>
    </div>
  </div>
  ${bodyHtml}
  <div class="report-footer">
    Generated by Botanic Journal — ${TODAY_LONG()}
  </div>
</body>
</html>`;
}

/**
 * Open a printable popup. User picks "Save as PDF" in their browser's print dialog.
 * Falls back to a same-window blob if popups are blocked.
 */
export function exportAsPDF(title, bodyHtml) {
  const doc = buildHtmlDocument(title, bodyHtml);
  const win = window.open('', '_blank');
  if (!win) {
    // Popup blocked → open in current window via blob
    const blob = new Blob([doc], { type: 'text/html' });
    const url  = URL.createObjectURL(blob);
    window.open(url, '_blank');
    return;
  }
  win.document.open();
  win.document.write(doc);
  win.document.close();

  // Trigger the print dialog after the page renders (and images load)
  win.onload = () => {
    setTimeout(() => {
      try { win.focus(); win.print(); } catch (e) { /* ignore */ }
    }, 250);
  };
}

/**
 * Download as a .doc file. Word and Google Docs open HTML-content .doc files perfectly.
 */
export function exportAsWord(title, bodyHtml) {
  const doc = buildHtmlDocument(title, bodyHtml);
  // The MS-Word HTML pre-amble + the proper MIME type makes Word treat this as native
  const preamble =
    '<html xmlns:o="urn:schemas-microsoft-com:office:office" ' +
         'xmlns:w="urn:schemas-microsoft-com:office:word" ' +
         'xmlns="http://www.w3.org/TR/REC-html40">';
  const wrapped = doc.replace('<html lang="en">', preamble);

  const blob = new Blob(['﻿', wrapped], { type: 'application/msword' });
  const url  = URL.createObjectURL(blob);

  const safeName = String(title || 'report').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeName || 'report'}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Tiny helper — escape user-supplied text for safe HTML embedding.
 */
export function escHtml(str) {
  if (str == null) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
